server:
  port: 8001

spring:
  application:
    name: short-link-project
  datasource:
    # ShardingSphere 对 Driver 自定义，实现分库分表等隐藏逻辑
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # ShardingSphere 配置文件路径
    url: jdbc:shardingsphere:classpath:shardingsphere-config-${database.env:dev}.yaml
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  mvc:
    view:
      prefix: /templates/
      suffix: .html
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

short-link:
  domain:
    default: nurl.ink:8001
  stats:
    locale:
      amap-key: a31216cf185fd2d9a3ef4cafdc7c5784
  goto-domain:
    white-list:
      enable: true
      names: '知乎,掘金,博客园'
      details:
        - zhihu.com
        - juejin.cn
        - cnblogs.com

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml


rocketmq:
#  指定 RocketMQ 的 NameServer 地址，生产者和消费者需要连接到 NameServer 才能发现 Broker 并进行消息发送或消费。
  name-server: common-rocketmq-dev.magestack.cn:9876
  producer:
#    指定生产者组（Producer Group）的名称，生产者组用于管理多个生产者实例。
    group: short-link_project-service_stats-save_pg_wangsibo
#    指定生产者发送消息的主题（Topic）
    topic: short-link_project-service_topic_wangsibo
#    设置发送消息的超时时间，单位是毫秒（ms）。
    send-message-timeout: 2000
#    同步消息发送失败时的重试次数。
    retry-times-when-send-failed: 1
#    异步消息发送失败时的重试次数。
    retry-times-when-send-async-failed: 1
  consumer:
#    指定消费者组（Consumer Group）的名称，消费者组用于多个消费者实例共同消费一个 Topic 的消息。
    group: short-link_project-service_stats-save_cg_wangsibo